.PHONY: clean All

All:
	@echo "----------Building project:[ MineSweeperGD - Debug ]----------"
	@cd "Labb5MineSweeper\mineSweeperGD\MineSweeperGD" && "$(MAKE)" -f  "MineSweeperGD.mk" && "$(MAKE)" -f  "MineSweeperGD.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ MineSweeperGD - Debug ]----------"
	@cd "Labb5MineSweeper\mineSweeperGD\MineSweeperGD" && "$(MAKE)" -f  "MineSweeperGD.mk" clean
